sudo: false
language: go
go:
  - 1.9
  - master
install:
  - go get github.com/golang/lint/golint
  - go get github.com/golang/dep/cmd/dep
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - dep ensure
script:
  # style
  - golint -set_exit_status $(go list ./...)
  - go vet -v ./...
  # build
  - go build -v ./...
  # quick testing
  - go test -v ./...
  # extensive testing
  - |
      echo "" > coverage.txt
      for FNAME in $(go list ./... | grep -v vendor); do
        go test -race -coverprofile=profile.out -covermode=atomic ${FNAME}
        if [ -f profile.out ]; then
          cat profile.out >> coverage.txt
          rm profile.out
        fi
      done
after_success:
  - bash <(curl -s https://codecov.io/bash)
